name: biobb_wf_autoencoder
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_pytorch
  - biobb_gromacs
  - biobb_analysis
  - jupyter
  - numpy
  - mdtraj
  - nglview 
  - ipywidgets
  - requests
  - matplotlib
