name: biobb_wf_autoencoder
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_pytorch==5.2.0
  - biobb_analysis==5.2.0
  - biobb_gromacs==5.2.0
  - biobb_io==5.2.0
  - numpy
  - nglview 
  - ipywidgets
  - requests
  - matplotlib
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
