name: biobb_wf_autoencoder
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_pytorch==5.1.0
  - biobb_analysis==5.1.0
  - biobb_gromacs==5.1.0
  - numpy
  - mdtraj
  - nglview 
  - ipywidgets
  - requests
  - matplotlib
